name: test

on: workflow_dispatch

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sometimes you gotta run run run run run"
      - run: echo "take a drag or two"
        
  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflows can work in parallel"

  job-3:
    runs-on: ubuntu-latest
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "run run run run run"
      - run: echo "gypsy death and you"
